### ISSUE TITLE
Inquery about the convexity

### ISSUE THREAD

**Issue by yuhui-xie** [UMich-BipedLab/global_pose_estimation_for_optimal_shape#1]
Hello, your work is really wonderful. 
But I'm a bittle of confused, may I ask why you choose to keep convexity when optimize the shape?

**Comment by brucejk** [comment]
Hi,

Thanks for using this repo and your question! 

Keeping the shape convex makes it have a large and consistent face/area for LiDAR to detect. 

When I first optimize the shape without the convexity constraints, some part of the shape becomes too narrow for LiDAR to have enough returns on the narrow area.  

Hope this answers your question. 

Please let me know if you have other questions. I will try my best to answer!
